CREATE TABLE IF NOT EXISTS scenarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  strategy_key VARCHAR(50) NOT NULL,
  params JSON NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
